### ISSUE TITLE
App fails to start OS X

### ISSUE THREAD

**Issue by hypernova1912** [ari-zah/gaiasandbox#54]
Whenever I load Gaia Sandbox, it loads, stays open with no window for a few seconds, then shuts down. I know it works on my system because it launched the first time. There is no .gaiasandbox folder anywhere on my system. (Yes, I searched in hidden files.) I am on OS X 10.11.3. Am I doing something wrong? I have tried deleting and reinstalling the application file twice, once from the same DMG and once from a new one. My error.log said this:

java.util.MissingResourceException: Can't find bundle key gui.gaia.attitude
	at com.badlogic.gdx.utils.I18NBundle.get(I18NBundle.java:436)
	at gaia.cu9.ari.gaiaorbit.desktop.gui.swing.I18nJFrame.txt(I18nJFrame.java:19)
	at gaia.cu9.ari.gaiaorbit.desktop.gui.swing.ConfigDialog.initialize(ConfigDialog.java:763)
	at gaia.cu9.ari.gaiaorbit.desktop.gui.swing.ConfigDialog.<init>(ConfigDialog.java:112)
	at gaia.cu9.ari.gaiaorbit.desktop.GaiaSandboxDesktop.init(GaiaSandboxDesktop.java:150)
	at gaia.cu9.ari.gaiaorbit.desktop.GaiaSandboxDesktop.main(GaiaSandboxDesktop.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:65)

**Comment by langurmonkey** [comment]
Oh, I see, a few keys are missing in the translation files. I will add them and close the issue. In the meantime, you can select English (UK) or get the translation files from the source. I will post a link once the commit is done.

**Comment by langurmonkey** [comment]
The links to get the new translations:

[English (US)](https://github.com/ari-zah/gaiasandbox/blob/0e5e84fc1e1fa209114f5308bfeda9bf9d0a9084/android/assets/i18n/gsbundle_en_US.properties)
[German](https://github.com/ari-zah/gaiasandbox/blob/0e5e84fc1e1fa209114f5308bfeda9bf9d0a9084/android/assets/i18n/gsbundle_de.properties)
[Catalan](https://github.com/ari-zah/gaiasandbox/blob/0e5e84fc1e1fa209114f5308bfeda9bf9d0a9084/android/assets/i18n/gsbundle_ca.properties)
[Spanish](https://github.com/ari-zah/gaiasandbox/blob/0e5e84fc1e1fa209114f5308bfeda9bf9d0a9084/android/assets/i18n/gsbundle_es.properties)

You should copy these to the `i18n` folder in your `gaiasandbox` installation folder. These are for the development version, but hopefully they will work with the latest release as well.
